/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dxf.DXF;
import java.awt.BorderLayout;
import pozo.Area;
import pozo.Pozo;
import zonaproteccion.JPFondo;

/**
 *
 * @author ricuesta
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    private Pozo pozo;
    private Area area;
    private DXF dxf;

    public FPrincipal() {
        System.out.println("Carga la vista principal.");
        initComponents();
        pozo = null;
        JPFondo fondo = new JPFondo();
        this.add(fondo, BorderLayout.CENTER);
        this.pack();
    }

    public void setPozo(Pozo pozo) {
        this.pozo = pozo;
    }

    public Pozo getPozo() {
        return pozo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        GestionarPozo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        RadioDeProteccion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RICZon");
        setPreferredSize(new java.awt.Dimension(408, 403));
        setResizable(false);

        jMenu1.setText("Archivo");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestionar");

        GestionarPozo.setText("Gestionar de Pozo");
        GestionarPozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarPozoActionPerformed(evt);
            }
        });
        jMenu2.add(GestionarPozo);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Calcular");

        RadioDeProteccion.setText("Radio de protección");
        RadioDeProteccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDeProteccionActionPerformed(evt);
            }
        });
        jMenu4.add(RadioDeProteccion);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionarPozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarPozoActionPerformed
        // TODO add your handling code here:
        FGPozo fgp = new FGPozo();
        fgp.setVisible(true);
        fgp.setfPrincipal(this);
        this.setEnabled(false);
        System.out.println("Muestra Formulario de gestion de pozo");
    }//GEN-LAST:event_GestionarPozoActionPerformed

    private void RadioDeProteccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDeProteccionActionPerformed
        // TODO add your handling code here:
        FDCalculo fdc = new FDCalculo();
        fdc.setfPrincipal(this);
        fdc.setVisible(true);        
        this.setEnabled(false);
        System.out.println("Muestra Formulario de factor de seguridad");
    }//GEN-LAST:event_RadioDeProteccionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GestionarPozo;
    private javax.swing.JMenuItem RadioDeProteccion;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
